version: 21
aliases:
  cache:
    lein_cache: &LEIN_CACHE
      key: lein-{{ .Environment.CACHE_VERSION }}-{{ checksum "project.clj" }}
      paths:
        - /home/node/.lein
        - /home/node/.m2
  containers:
    docker: &DEFAULT
      - image: jesiio/build-bus:latest
        user: node
        environment:
          JVM_OPTS: -Xmx3200m
          DEBUG: 1
  commands:
    cancel_redundant: &CANCEL_REDUNDANT
      run:
        name: Check & Cancel Redundant Build
        command: 'cancel-redundant-builds.sh'
jobs:
  deps:
    docker: *DEFAULT
    steps:
      - *CANCEL_REDUNDANT
      - checkout
      - restore_cache:
          <<: *LEIN_CACHE
      - run: './quarrelsome.clj deps'
      - save_cache:
          <<: *LEIN_CACHE
  lint:
    docker: *DEFAULT
    steps:
      - *CANCEL_REDUNDANT
      - checkout
      - restore_cache:
          <<: *LEIN_CACHE
      - run: './quarrelsome.clj lint'
  test:
    docker: *DEFAULT
    steps:
      - *CANCEL_REDUNDANT
      - checkout
      - restore_cache:
          <<: *LEIN_CACHE
      - run: './quarrelsome.clj test'
  docs:
    docker: *DEFAULT
    steps:
      - *CANCEL_REDUNDANT
      - checkout
      - restore_cache:
          <<: *LEIN_CACHE
      - run: './quarrelsome.clj test-docs'
  snapshot:
    docker: *DEFAULT
    steps:
      - *CANCEL_REDUNDANT
      - checkout
      - restore_cache:
          <<: *LEIN_CACHE
      - run: './quarrelsome.clj snapshot'
  release:
    docker: *DEFAULT
    steps:
      - *CANCEL_REDUNDANT
      - checkout
      - restore_cache:
          <<: *LEIN_CACHE
      - run: './quarrelsome.clj release'
workflows:
  version: 2
  build:
    jobs:
      - deps
      - lint:
          requires:
            - deps
      - test:
          requires:
            - deps
      - docs:
          requires:
            - lint
      - snapshot:
          requires:
            - lint
            - test
            - docs
          filters:
            branches:
              ignore: /^(master|develop)$/
      - release:
          requires:
            - test_clj
          filters:
            branches:
              only: master
